- name: Log playbook start
  shell: "echo -n 'Start: ' >> {{ logfile }}; date >> {{ logfile }}"
- name: Install baseline software
  package: pkg={{ item }} state=present
  with_items:
  - epel-release
  - wget
  - deltarpm
  - curl
  - open-vm-tools
  - yum-utils
  notify:
    - Reboot
- name: Install updates
  package: name=* state=latest
  notify:
    - Reboot
- name: Delete old kernels
  shell: package-cleanup --oldkernels --count=2 -y
- name: Log playbook stop
  shell: "echo -n 'Stop:  ' >> {{ logfile }}; date  >> {{ logfile }}; echo '' >> {{ logfile }}"
