--- # main playbook
#- hosts: all
#  gather_facts: no
#  become: yes
#  tasks:
#  - name: knock knock
#    ping:

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: os_configuration
      vars:
        logfile: "/var/log/ansible_os_configuration.log"
        proxy_ip_port: "10.0.5.1:8888"
  # FIXME
  #  - role: os_update
  #    vars:
  #      logfile: "/var/log/ansible_os_update.log"
